### PR TITLE
Add docker support.

### PR DESCRIPTION
**Pull request by johngian**
- Create Dockerfile for woodstock image
- Add scripts for both dev/prod envs
- Add docker-compose support for local development
- Add missing package required for using PostgreSQL
- Fix BASE_DIR path definition

### CODE REVIEW

**Comment by johngian** [comment]
@akatsoulas r?

**Comment by johngian** [comment]
Fixes #17

**Comment by johngian** [comment]
Fixes #12

**Comment by akatsoulas** [comment]
Why not just use sqlite?

**Comment by comzeradd** [comment]
I think it's good to have our dev/docker environment as close to production as possible. I'd choose the same database engine we'll use on production.

**Comment by johngian** [comment]
I don't have any strong opinions between MySQL/PostgreSQL.
The reason that SQlite is not an option for this, is that it requires persistent storage and this might be tricky, since we haven't deployed docker with persistent storage before.

**Pull request merged**
